// File normally generated by FlutterFire CLI. This is a stand-in.
// See GETSTARTED.md for details.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  @Deprecated('Run `flutterfire configure` to re-generate this file')
  static FirebaseOptions get currentPlatform {
    throw UnimplementedError(
        'Generate this file by running `flutterfire configure`. '
        'See GETSTARTED.md for details.');
  }
}
